version: "3.9"

x-common-configuration: &common-configuration
  image: itsniklas/domjudge-judgehost-nightly:latest
  restart: on-failure:5
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
  privileged: true
  env_file:
    - judgehost.env

services:
  judgedaemon0:
    <<: *common-configuration
    hostname: judgedaemon0
    container_name: judgedaemon0
    environment:
      DAEMON_ID: 0

  judgedaemon1:
    <<: *common-configuration
    hostname: judgedaemon1
    container_name: judgedaemon1
    environment:
      DAEMON_ID: 1

  judgedaemon2:
    <<: *common-configuration
    hostname: judgedaemon2
    container_name: judgedaemon2
    environment:
      DAEMON_ID: 2

  judgedaemon3:
    <<: *common-configuration
    hostname: judgedaemon3
    container_name: judgedaemon3
    environment:
      DAEMON_ID: 3
